### ISSUE TITLE
README.md Import Example

### ISSUE THREAD

**Issue by drettt** [FergM/fattails#10]
Hi. In the example in the readme.md, I think the import is missing the metrics part. I think it should be from fattails import metrics and then you can use metrics.mad(...). Hope this helps.

**Comment by FergM** [comment]
Thanks! This is new for `v0.0.3`.

I uploaded `v0.0.3` to the package index just now. If you're using pip you can get it with `python -m pip install --upgrade fattails` 

Old example (Still works)
```
import fattails

mean_deviation = fattails.metrics.mad([1,2,3])
````

New Example (Quick Access)
```
import fattails

mean_deviation = fattails.mad([1,2,3])
```

Let me know if any issues!
